export default {
  defaultTheme: 'default-light',
  themes: {
    'default-light': {
      dark: false,
      colors: {
        primary: '#F44336',
        secondary: '#9E9E9E',
        accent: '#F44336',
        error: '#B71C1C',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#F57C00',
        background: '#FAFAF8',
        surface: '#FFFFFF',
        'on-background': '#1C1917',
        'on-surface': '#1C1917',
      },
    },
    'default-dark': {
      dark: true,
      colors: {
        primary: '#EF5350',
        secondary: '#616161',
        accent: '#EF5350',
        error: '#B71C1C',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#F57C00',
        background: '#0F172A',
        surface: '#1E293B',
        'on-background': '#F1F5F9',
        'on-surface': '#F1F5F9',
      },
    },
    'electron-neon-light': {
      dark: false,
      colors: {
        primary: '#00B4D8',
        secondary: '#0077B6',
        accent: '#00B4D8',
        error: '#B71C1C',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#F57C00',
        background: '#E0F7FA',
        surface: '#FFFFFF',
        'on-background': '#004D40',
        'on-surface': '#004D40',
      },
    },
    'electron-neon-dark': {
      dark: true,
      colors: {
        primary: '#00F5D4',
        secondary: '#7B2CBF',
        accent: '#00F5D4',
        error: '#B71C1C',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#F57C00',
        background: '#0A0F1D',
        surface: '#131B2E',
        'on-background': '#E0F7FA',
        'on-surface': '#E0F7FA',
      },
    },
    'tokyo-day': {
      dark: false,
      colors: {
        primary: '#34548A',
        secondary: '#89DDF3',
        accent: '#34548A',
        error: '#B71C1C',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#F57C00',
        background: '#E1E2E7',
        surface: '#F2F3F7',
        'on-background': '#3760BF',
        'on-surface': '#3760BF',
      },
    },
    'tokyo-night': {
      dark: true,
      colors: {
        primary: '#7AA2F7',
        secondary: '#565F89',
        accent: '#7AA2F7',
        error: '#B71C1C',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#F57C00',
        background: '#1A1B26',
        surface: '#24283B',
        'on-background': '#C0CAF5',
        'on-surface': '#C0CAF5',
      },
    },
    'newspaper-light': {
      dark: false,
      colors: {
        primary: '#111111',
        secondary: '#555555',
        accent: '#111111',
        error: '#B71C1C',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#F57C00',
        background: '#F4F4F0',
        surface: '#FFFFFF',
        'on-background': '#111111',
        'on-surface': '#111111',
      },
    },
    'newspaper-dark': {
      dark: true,
      colors: {
        primary: '#EAEAEA',
        secondary: '#AAAAAA',
        accent: '#EAEAEA',
        error: '#B71C1C',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#F57C00',
        background: '#121212',
        surface: '#1E1E1E',
        'on-background': '#EAEAEA',
        'on-surface': '#EAEAEA',
      },
    },
  },
};
